application: shared-flat-expenses
version: version-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# - url: /questions.*
#   script: handlers.questions_handler.app

- url: /users
  script: handlers.main_handler.app

- url: /items
  script: handlers.main_handler.app

- url: /
  script: handlers.main_handler.app
  # static_files: public/index.html
  # upload: public/index.html
  login: required

- url: /
  static_dir: public

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^public$
